[build-system]
requires = [
    "typing~=3.7.4.3",
    "pyserial~=3.4",
    "crcmod~=1.7",
    "requests~=2.25.1",
    "configparser~=5.0.2",
    "simplejson~=3.16.0",
    "paho-mqtt~=1.5.1"
]
build-backend = "setuptools.build_meta"